### ISSUE TITLE
about model zoo

### ISSUE THREAD

**Issue by wanboyang** [ruotianluo/ImageCaptioning.pytorch#109]
Does the  "FC or other model+new_self_critical" in model zoo mean "FC or other model" use the training method proposed in paper "Discriminability objective for training descriptive captions" ?
Look forward to your favourable reply.

**Comment by wanboyang** [comment]
I has some question about model zoo:
1. "FC+self_critical" can be considered as the  pretrained model of [1]?
2. "Att2in+new_self_critical" can be considered as the  pretrained model of [2]?
3. "UpDown+self_criticall" can be considered as the  pretrained model of [3]?

[1]Rennie S J, Marcheret E, Mroueh Y, et al. Self-critical sequence training for image captioning[C]//Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition. 2017: 7008-7024.
[2]Luo R, Price B, Cohen S, et al. Discriminability objective for training descriptive captions[C]//Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition. 2018: 6964-6974.
[3] Anderson P, He X, Buehler C, et al. Bottom-up and top-down attention for image captioning and visual question answering[C]//Proceedings of the IEEE conference on computer vision and pattern recognition. 2018: 6077-6086.

**Comment by ruotianluo** [comment]
1 == FC in [1]
2 is in my paper https://arxiv.org/abs/2003.09971. "att2in+self_critical" is Att2in in [2] (roughly speaking, there may be some difference in architecture detail).
3 correct.

**Comment by wanboyang** [comment]
> 1 == FC in [1]
> 2 is in my another paper https://arxiv.org/abs/2003.09971. (Discriminability is in my another repo https://github.com/ruotianluo/DiscCaptioning) "att2in+self_critical" is Att2in in [1] (roughly speaking, there may be some difference in architecture detail).
> 3 correct.

Thanks for your reply.
1."att2in+self_critical" seems is trained by Bottom-up features, can you provide an "att2in+self_critical"  pretained model that trained with Resnet101 feature?
2. In  repo (https://github.com/ruotianluo/DiscCaptioning)(url) , It seems you use a data-split different from standard karpathy's split, and in [https://github.com/ruotianluo/DiscCaptioning/issues/16](url), you said the datasplit of neuraltalk2 is different from karpathy ones, could you provide details about the difference, or provide a link of introducting data-split in neuraltalk2?
3.Could you provide a pretrained model of [2] by using standard karpathy's split?
Thanks again

**Comment by ruotianluo** [comment]
1. https://drive.google.com/drive/folders/0B7fNdx_jAqhtQ1E0NUUyRjVtb0U?usp=sharing
2. neuraltalk2 (specific to that repo) randomly select train/val/test from all the coco images, while in karparthy split, the val and test were chosen from coco val2014.
3. I actually suggest running it by yourself, I think it's fairly easy to run, and should be able to get better results than what's in the paper. All the models I trained for that project are already archived, it's a little bit complicated to mine in that. You can try to run it first; if you have any problem, let me see how I can retrieve from the archived data.

**Comment by wanboyang** [comment]
Thank for your  patiences

**Comment by wanboyang** [comment]
when I used the pretained models of “att2in+self_critical” provided in line[https://drive.google.com/drive/folders/0B7fNdx_jAqhtQ1E0NUUyRjVtb0U?usp=sharing](url), the model only generate some error sentences, like one image in ![image](https://github.com/wanboyang/temp_images/blob/master/Untitled%20Folder_3/accordion_01276.jpg)
 “att2in+self_critical”  caption is "a black dark looking in a dark dark window"
“fc+self_critical" caption is "a black and white cat sitting on top of a table"


and  “att2in+self_critical”output a lot of  similar sentences like
"a black and white dark looking in the dark"，
‘a black and white dark dark looking in the dark’，
"a black and white UNK in the dark" and so on. It seems something wrong with weights of line[https://drive.google.com/drive/folders/0B7fNdx_jAqhtQ1E0NUUyRjVtb0U?usp=sharing](url).

In my experiments, I use default setting: 
1. resnet101
2.dataloaderaw.
Can you check the weights [https://drive.google.com/drive/folders/0B7fNdx_jAqhtQ1E0NUUyRjVtb0U?usp=sharing](url)

I provide some images and captions generated in my experiments for [checking](https://github.com/wanboyang/temp_images)
the  “att2in+self_critical” captions of above images are:
accordion_01276.jpg:"a black dark looking in a dark dark window'
ccordion_00019.jpg:"a black and white dark dark looking in the dark"
airplane_00015.jpg:a black and white UNK in the dark
airplane_00016.jpg:"a black and white UNK in the dark"
airplane_00018.jpg:"a black and white picture of a black and white picture of a"
artichoke_00007.jpg:"a dark dark looking in the dark dark"


the  “fc+self_critical” captions of above images are:
accordion_01276.jpg:"a black and white cat sitting on top of a table'
ccordion_00019.jpg:"a close up of a orange on the top of a tree"
airplane_00015.jpg:'a close up of a UNK on a table'
airplane_00016.jpg:"a close up of a baseball bat on a field"
airplane_00018.jpg:"a close up of a UNK on top of a table"
artichoke_00007.jpg:"a close up of a orange on top of a table"
