### ISSUE TITLE
The demo colab notebook is erroring out

### ISSUE THREAD

**Issue by rohitsaraf17** [ruotianluo/ImageCaptioning.pytorch#122]
The demo colab notebook is erroring out:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-e4cc7fbaecb3> in <module>()
     22 from maskrcnn_benchmark.modeling.detector import build_detection_model
     23 from maskrcnn_benchmark.structures.image_list import to_image_list
---> 24 from maskrcnn_benchmark.utils.model_serialization import load_state_dict
     25 
     26 

/content/vqa-maskrcnn-benchmark/maskrcnn_benchmark/utils/imports.py in <module>()
      2 import torch
      3 
----> 4 if torch._six.PY3:
      5     import importlib
      6     import importlib.util

AttributeError: module 'torch._six' has no attribute 'PY3'

**Comment by ruotianluo** [comment]
Try if you can manually set this value to True, before importing vqamaskrcnn

**Comment by rohitsaraf17** [comment]
Worked!
