### ISSUE TITLE
what is the difference between two cider modules

### ISSUE THREAD

**Issue by HiLittleFriend** [ruotianluo/ImageCaptioning.pytorch#123]
Coco has a cider submodule. And there is another cider module in the root dir. What's the difference between them. Thank you.

**Comment by ruotianluo** [comment]
The cider submodule is used for self critical training (with some customized optimization for speed up). When evaluation, the coco-caption submodule is used.

**Comment by HiLittleFriend** [comment]
Thanks a lot. I just see the cache part.
