### ISSUE TITLE
a bug when run tools/eval.py--nothing happens when running the file with the same model for second time

### ISSUE THREAD

**Issue by KentHwang1** [ruotianluo/ImageCaptioning.pytorch#124]
I run the tool/eval.py for testing in resnet model,it runs normally for the first time :
![first-time](https://user-images.githubusercontent.com/50869722/118419812-b1b80c00-b6ef-11eb-8b8c-3819cebb9d20.png)
but when i run the tool/eval.py with the same order line,there is nothing happening like this:
![second-time](https://user-images.githubusercontent.com/50869722/118420100-90a3eb00-b6f0-11eb-9196-51c9f44b068d.png)

could you please tell me how I could solve the problem?how to make it normal when every time i run it for testing ?Thank you so much!

**Comment by ruotianluo** [comment]
add --force in the command.

(I add some caching to avoid reevaluation, I guess that should not be default.)

**Comment by KentHwang1** [comment]
It works! Thank you so much!
