### ISSUE TITLE
Evaluating the raw image

### ISSUE THREAD

**Issue by alice-cool** [ruotianluo/ImageCaptioning.pytorch#131]
Evaluate on raw images
Note: this doesn't work for models trained with bottomup feature. Now place all your images of interest into a folder, e.g. blah, and run the eval script:

$ python tools/eval.py --model model.pth --infos_path infos.pkl --image_folder blah --num_images 10

The image captioning performance is not high. 
And run once, the next time will throw errors,such as the below picture
![image](https://user-images.githubusercontent.com/16870890/128008101-84e99412-1397-42af-918c-0531698d368b.png)

**Comment by ruotianluo** [comment]
Try add --language_eval 0

**Comment by alice-cool** [comment]
Thanks for your reply. But it doesn't work.&nbsp;



---原始邮件---
发件人: "Ruotian(RT) ***@***.***&gt;
发送时间: 2021年8月3日(星期二) 晚上9:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ruotianluo/ImageCaptioning.pytorch] Evaluating the raw image (#131)




 
Try add --language_eval 0
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ruotianluo** [comment]
Try --force 1? And, what features did you use to train?

**Comment by alice-cool** [comment]
Dear scholar,
I just evaluate on the raw image with your provided pretrained weights file. 
![image](https://user-images.githubusercontent.com/16870890/128034319-7315e1e0-bcc4-4ba4-8dd8-06b90c2ed646.png)
![image](https://user-images.githubusercontent.com/16870890/128034362-a7e3a4c1-c614-4f07-8ff5-f597943c4fa9.png)
But My image didn't include the dog, but the produced caption always has these confusing words

![image](https://user-images.githubusercontent.com/16870890/128034548-d3f8f982-878c-43d5-b9ca-37b8123f363e.png)

**Comment by ruotianluo** [comment]
Can you send one of this image to me?

**Comment by alice-cool** [comment]
Dear scholar,
 Thanks for your timely reply.
![24146](https://user-images.githubusercontent.com/16870890/128041168-97325b4e-ef81-49b4-9269-84f94d2ec6be.jpg)
![2386621](https://user-images.githubusercontent.com/16870890/128041176-63fd68bc-1806-4ea9-a5fe-d9852e796b05.jpg)
![2413658](https://user-images.githubusercontent.com/16870890/128041182-e2078c69-2a6d-44e6-ad91-465c2bfb5a5f.jpg)
![2414602](https://user-images.githubusercontent.com/16870890/128041187-6a2fee0b-e8c7-4668-983a-ae11599829c2.jpg)
![woman_fish](https://user-images.githubusercontent.com/16870890/128041189-215d8abd-e5dc-43e3-b6af-5feff358f651.jpg)

**Comment by ruotianluo** [comment]
It works on my side it seems. Did you download the resnet-101.pth as in https://github.com/ruotianluo/ImageCaptioning.pytorch/blob/master/data/README.md#image-features-option-1-resnet-features ?

**Comment by alice-cool** [comment]
Thanks for your reply. I will try it tomorrow Thanks for your concern. good night



---原始邮件---
发件人: "Ruotian(RT) ***@***.***&gt;
发送时间: 2021年8月3日(星期二) 晚上11:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ruotianluo/ImageCaptioning.pytorch] Evaluating the raw image (#131)




 
It works on my side it seems. Did you download the resnet-101.pth as in https://github.com/ruotianluo/ImageCaptioning.pytorch/blob/master/data/README.md#image-features-option-1-resnet-features ?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alice-cool** [comment]
It must be the resnet101 I download from the pytorch library models. 
And I replace it with your pointed data file
Some is good ,Some is bad.
![image](https://user-images.githubusercontent.com/16870890/128108280-71250e58-8db3-49fc-9c0a-285339bf2973.png)
