### ISSUE TITLE
about dataset_coco.json

### ISSUE THREAD

**Issue by gcj2021** [ruotianluo/ImageCaptioning.pytorch#141]
抱歉打扰了，最近想制作一个自己的数据集，这个文件是如何产生的？我该如何自己制作这个文件呢

**Comment by ruotianluo** [comment]
其实结构挺简单的，模仿一下就可以了

**Comment by gcj2021** [comment]
我大概解析了一下格式。。。
有做这个json文件的源代码吗？我输入对应图片和描述，能生成这个json文件的。
是不是做完这个文件，其他文件不需要改动，按顺序就可以得到最后结果呢？
我比较菜，感谢回复

**Comment by ruotianluo** [comment]
嗯，我自己做过，但是找不到了。

基本上是这样的。
可能还要弄一个evaluation的json file，如果需要算bleu什么的

**Comment by gcj2021** [comment]
感谢！！
我琢磨一下写个脚本吧。数据集要自己做，唉，太苦了。

**Comment by lalaha1** [comment]
> 感谢！！ 我琢磨一下写个脚本吧。数据集要自己做，唉，太苦了。

你好，打扰啦，我也遇到了这个问题。请问如果想做自己的数据集，类似dataset_coco.json文件应该怎么生成啊？

**Comment by gcj2021** [comment]
> > 感谢！！ 我琢磨一下写个脚本吧。数据集要自己做，唉，太苦了。
> 
> 你好，打扰啦，我也遇到了这个问题。请问如果想做自己的数据集，类似dataset_coco.json文件应该怎么生成啊？

解析一下json格式，仿照那个格式就行
