### ISSUE TITLE
the differences between labels and gts

### ISSUE THREAD

**Issue by wlufy** [ruotianluo/ImageCaptioning.pytorch#147]
您好，我在读`loss_wrapper.py`中的代码时遇到一些问题，想请问一下，`forward`函数中的`labels`和`gts`两个参数分别表示什么含义呢？
`def forward(self, fc_feats, att_feats, labels, masks, att_masks, gts, gt_indices,
                sc_flag, struc_flag, drop_worst_flag):`
谢谢！

**Comment by ruotianluo** [comment]
labels是一个sample一个caption。gts是对应这个sample的所有gt captions。

Ruotian Luo

**Comment by wlufy** [comment]
谢谢您的回复，但我还是不太理解：

1. 我在调试时发现(batch_size=10)，`labels`的shape是`[10, 5, 18]`，`gts`的shape是`[10, 5, 16]`，而且二者的内容能够对应起来，所以我不是很理解`labels是一个sample一个caption`这句话。我对于sample的理解是：输入batch个特征，随机采样，输出batch个caption。不知道我的理解有没有问题？
2. 我在dataloader里看到这部分代码`gts.append(self.label[self.label_start_ix[ix] - 1: self.label_end_ix[ix]])`，这看起来gts只是对labels做了截断？

您可以更详细地解释一下吗？
非常抱歉再次打扰您，谢谢！

**Comment by ruotianluo** [comment]
主要原因是这样的，gts是用于self critical stage的。labels是用在cross entropy stage。他们本质上都是ground truth。

你可以认为这两个我每次只用一个。（当然两个一起用也是可以的）

但是labels的5是根据seq per image来定的。而且10x5其实本质上就是50个sample。但是gts的5是因为coco一个图片5个caption，而且所有的5个caption是用于计算一个loss，所以虽然gts是10x5，但是batch size还是10。

**Comment by wlufy** [comment]
感谢您的及时回复！

我大概明白了：gts 和 labels 本质上是一个东西，都是 ground truth，只是它们在计算 loss 时的处理方式不同，是这样吗？
如果我用 labels 替换 gts，直接把 labels 用在self critical阶段，理论上是不是也可以work？

非常感谢！

**Comment by ruotianluo** [comment]
理论上是可以的，就是要再做一些处理。

Ruotian Luo

**Comment by wlufy** [comment]
我明白了，非常感谢您的解答！！
