### ISSUE TITLE
我在评估时遇到了一点问题

### ISSUE THREAD

**Issue by dyoung666** [ruotianluo/ImageCaptioning.pytorch#155]
老师您好 目前我已经在自己的中文数据集上取得了结果 并按照描述和结果的格式生成了json文件，但是评估完指标全是0，除了meteor指标，这显然不合常理，请问跟中文有关系吗，json文件的格式应该是正确的。谢谢！

**Comment by ruotianluo** [comment]
不makesense，你用的是中文专门的evaluation嘛

**Comment by dyoung666** [comment]
谢谢您的答复 我用的是您代码中的cococaption 按照captions_val2014.json和captions_val2014_fakecap_results.json的格式做了自己的中文json文件，描述看起来也比较成功 。

**Comment by dyoung666** [comment]
是的 非常抱歉浪费了您的时间 我发现我caption没有分词 十分感谢您的代码库，对我帮助很大 谢谢
