### ISSUE TITLE
请教一下原文中的公式

### ISSUE THREAD

**Issue by dyoung666** [ruotianluo/ImageCaptioning.pytorch#157]
罗老师，您好 我在阅读这个模型的原文时遇到了一点问题，在下面这个公式中
<img width="287" alt="image" src="https://user-images.githubusercontent.com/105112132/172582145-4e35247c-1701-4529-8cb0-72f8e91129b7.png">
右边括号中的两项是什么意思 有点不能理解，尤其是左边那个p-θ（w丨h）
谢谢！

**Comment by ruotianluo** [comment]
P就是模型的输出，每个词的概率。对sample出来的那个词，最右边的括号是模型输出的概率- 1,对其余的词就是模型输出的概率。
