### ISSUE TITLE
cocotalk_att/cocotalk_fc file is only 49+1 GB( by resnet101)

### ISSUE THREAD

**Issue by jacks1051** [ruotianluo/ImageCaptioning.pytorch#163]
Does anyone know why my cocotalk_att/cocotalk_fc file is 49+1 GB( by resnet101) , while the readme said it's about 200GB. 
Is anything wrong here?
The coco dataset contains 123,287 files. att_size is default 14.
Thank u for your time and hope your reply.

**Comment by ruotianluo** [comment]
The readme is probably outdated.

**Comment by jacks1051** [comment]
> The readme is probably outdated.
Thank you so much.  Based on your reply, I  think  my situation，the coco dataset(train2014 and val2014) is about 20G  and It  generates about 50G features，is reasonable.
