### ISSUE TITLE
Simple Test Collab Notebook No longer Works

### ISSUE THREAD

**Issue by AlexanderWeismannn** [ruotianluo/ImageCaptioning.pytorch#168]
Hi There,

I was attempting to test out the collab notebook but run into  `ImportError: cannot import name '_C' from 'maskrcnn_benchmark'` when stepping through the compilation of each cell. Has anyone else faced this issue and if so did they find a solution for it?

Cheers!

**Comment by AlexanderWeismannn** [comment]
[https://github.com/facebookresearch/maskrcnn-benchmark/issues/1313](url) Found a similar problem here.

Though examining the code im not sure exactly what should be changed. Ill attach some images below:

![image](https://user-images.githubusercontent.com/50328533/207119250-2169660c-d298-4250-b582-be291f11021f.png)

![image](https://user-images.githubusercontent.com/50328533/207119336-7b850108-795f-4ea7-9e21-e00f769d48d6.png)

**Comment by AlexanderWeismannn** [comment]
After more investigation there seems to be no issues on the maskrcnn page that are very related to this issue.

**Comment by ruotianluo** [comment]
use this, to install 1.7.0 pytorch
%pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by ruotianluo** [comment]
at least the same error won't appear.
