### ISSUE TITLE
Simple Colab Notebook Issue: No such file or directory: 'model-best.pth'

### ISSUE THREAD

**Issue by AlexanderWeismannn** [ruotianluo/ImageCaptioning.pytorch#170]
When running the cell below it seems that the 'model-best.pth' was not generated.

**Comment by AlexanderWeismannn** [comment]
![image](https://user-images.githubusercontent.com/50328533/208132247-6af47332-47de-4df3-bf55-404fbc4770ea.png)

**Comment by AlexanderWeismannn** [comment]
Quick update. I see that there are multiple "model-best.pth" on the google drive that i can use but im not sure which one specifically coincides with this particular test notebook.

**Comment by ruotianluo** [comment]
gdown cannot download properly any more for some reason. Is there one whose name has 12in it?

**Comment by AlexanderWeismannn** [comment]
None when i looked though it quickly. Ill look again and see.

**Comment by AlexanderWeismannn** [comment]
hmm yeah seems like an access issues with gdown. Ill see if there a work around maybe

**Comment by AlexanderWeismannn** [comment]
So gdown doesnt work on files that are too large and seem to be blocked by the virus detection scan not being able to be run. Downloading it manually fixed the issue.

**Comment by AlexanderWeismannn** [comment]
updates gdown `%pip install --upgrade --no-cache-dir gdown` and ran using `!gdown 1VmUzgu0qlmCMqM1ajoOZxOXP3hiC_qlL` fixed the problem.
