### ISSUE TITLE
应用其他数据集的问题

### ISSUE THREAD

**Issue by buyongbaoqian** [ruotianluo/ImageCaptioning.pytorch#178]
罗老师您好，我在使用您的模型在自己准备的数据集上训练的时候出现了矩阵不能相乘的问题，该数据集的json文件已经按照dataset_coco.json文件的格式准备好，在训练时报错，错误代码如下，请问可以提示一下该怎么解决吗

$ python tools/train.py --cfg configs/fc.yml --id fc
cider or coco-caption missing
DataLoader loading json file:  data/rsicdtalk.json
vocab size is  1256
DataLoader loading h5 file:  data/rsicdtalk_fc data/rsicdtalk_att data/cocotalk_box data/rsicdtalk_label.h5
max sequence length in data is 16
read 10921 image features
assigned 8734 images to split train
assigned 1094 images to split val
assigned 1093 images to split test
d:\imagecaptioning.pytorch-master1\captioning\data\dataloader.py:290: RuntimeWarning: Mean of empty slice.
  fc_feat = att_feat.mean(0)
Read data: 0.00298309326171875
Save ckpt on exception ...
model saved to ./log_fc\model.pth
Save ckpt done.
Traceback (most recent call last):
  File "D:\ImageCaptioning.pytorch-master1\tools\train.py", line 185, in train
    model_out = dp_lw_model(fc_feats, att_feats, labels, masks, att_masks, data['gts'], torch.arange(0, len(data['gts'])), sc_flag, struc_flag, drop_worst_flag)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\parallel\data_parallel.py", line 169, in forward
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (10x0 and 2048x512)

**Comment by ruotianluo** [comment]
你是在一个gpu还是多个gpu上train？

**Comment by buyongbaoqian** [comment]
在一个GPU训练
