### ISSUE TITLE
获取dataset_coco.json的页面404 not found

### ISSUE THREAD

**Issue by yeeeeee0** [ruotianluo/ImageCaptioning.pytorch#184]
您好，我根据您在data里提示去https://www.cs.stanford.edu/people/karpathy/deepimagesent/caption_datasets.zip，这个网页下载dataset_coco.json，但是这个网页404了，请问还有别的下载途径吗？非常感谢！

**Comment by ruotianluo** [comment]
http://cs.stanford.edu/people/karpathy/deepimagesent/caption_datasets.zip

**Comment by yeeeeee0** [comment]
非常感谢！！

**Comment by yeeeeee0** [comment]
老师，这个网址也404了，请问还有别的途径吗？
