### ISSUE TITLE
关于train use self-critical

### ISSUE THREAD

**Issue by sunmoxian** [ruotianluo/ImageCaptioning.pytorch#188]
报错：ModuleNotFoundError: No module named 'cider'
检查cider中readme说是python2.7，但我现在用的是3.7，是这个原因吗？

**Comment by ruotianluo** [comment]
你用的是submodule里面的cider吗？

**Comment by ruotianluo** [comment]
如果是的话，可能就是没成功驾到sys.path里面，可能你可以手动在环境变量里面加

**Comment by sunmoxian** [comment]
> 你用的是submodule里面的cid

**Comment by sunmoxian** [comment]
> 如果是的话，可能就是没成功驾到sys.path里面，可能你可以手动在环境变量里面加

是的，我试试添加环境变量

**Comment by sunmoxian** [comment]
谢谢老师
