### ISSUE TITLE
A question about evaluation funciton

### ISSUE THREAD

**Issue by lxtGH** [ruotianluo/ImageCaptioning.pytorch#27]
Sorry again for bother you. But I can't understand the code 
in the class  LanguageModelCriterion
what does the **mask** do ? 
I don't understand the loss calculation process ,  Is that is to calculate the poster probabilty ?
Can you tell me or give some reference. Many thanks!!!

**Comment by ruotianluo** [comment]
it is because the captions have different length. They are padded to the same length when being batched. 
The mask is used to compute only the part that is real words.

**Comment by lxtGH** [comment]
Got it ！ Sorry for late reply， thank you very much !!!!!!
