### ISSUE TITLE
The attention mechanism of '''top-down'' is different from that of  ''show attend and tell'', but they seem the same in your code.

### ISSUE THREAD

**Issue by wjyang2017** [ruotianluo/ImageCaptioning.pytorch#29]

**Comment by ruotianluo** [comment]
They are not the same. (However just note that my show attend and tell is a simplified version.)

**Comment by wjyang2017** [comment]
https://github.com/ruotianluo/ImageCaptioning.pytorch/blob/13516dfd905b0755c28c922e39722ce09ca4f689/models/AttModel.py#L374
"Top-down"  has not the trainable attention weights. This is the most significant difference between “top-down”and "show attend and tell".

**Comment by ruotianluo** [comment]
Maybe I understand incorrectly, I think this `self.attention` is doing equation 3 and 4 in the paper.

**Comment by wjyang2017** [comment]
Equation 4  works as part of  background. Thanks for your code, learned a lot.
