### ISSUE TITLE
if i want to train cnn and LSTM，how should i do????

### ISSUE THREAD

**Issue by 123moon** [ruotianluo/ImageCaptioning.pytorch#43]

**Comment by koustav123** [comment]
+1.
Did you implement an end to end training for both the CNN and LSTM?

**Comment by swingsky** [comment]
I am sorry I don't find the fine-tune branch.

**Comment by ruotianluo** [comment]
@swingsky https://github.com/ruotianluo/ImageCaptioning.pytorch/tree/with_finetune

**Comment by swingsky** [comment]
Get it. Thanks.
