### ISSUE TITLE
What are the abbreviation of "fc" and "att" meaning?

### ISSUE THREAD

**Issue by thumbe12856** [ruotianluo/ImageCaptioning.pytorch#46]
I can see that the abbreviation of "fc" and "att" are full of the whole project. And it seems that come from [`misc/resnet_utils.py`,](https://github.com/ruotianluo/ImageCaptioning.pytorch/blob/master/misc/resnet_utils.py) but no any comment mentions about their meaning.

Could someone tell me what are the abbreviation of ["fc"](https://github.com/ruotianluo/ImageCaptioning.pytorch/blob/master/misc/resnet_utils.py#L24) and ["att"](https://github.com/ruotianluo/ImageCaptioning.pytorch/blob/master/misc/resnet_utils.py#L25) meaning and what are the two variables doing?

Thanks.

**Comment by ruotianluo** [comment]
They are the input feature of the models. In principle, att is a feature with spatial dimensions (Cxdxd) while the second and third dimension are spatial dimensions. And fc is a length C vector.

**Comment by Silence1995** [comment]
@ruotianluo, does _C_ vector mean LSTM's memory as the mention in the [paper](https://arxiv.org/pdf/1502.03044.pdf) at section 3.1.2?

**Comment by ruotianluo** [comment]
No. C is 2048 if you are using resnet.

**Comment by thumbe12856** [comment]
I got it!  Thanks @ruotianluo a lot.

**Comment by grizzly101** [comment]
fc is fully connected, not sure what att is

**Comment by ruotianluo** [comment]
att is short for attention desire. Its the spatial feature of the image, which is what the attention module operates on.
