### ISSUE TITLE
the paper pointed that fc is generated by faster rcnn, I find you use resnet instead.

### ISSUE THREAD

**Issue by xuxuzhou** [ruotianluo/ImageCaptioning.pytorch#56]
Will it influence the result? and I cannot understand the att contains 14x14 in myResnet, what does it mean? Thanks

**Comment by ruotianluo** [comment]
Which paper? yes it does. Faster rcnn is better.

**Comment by xuxuzhou** [comment]
the paper about the topdown model

**Comment by ruotianluo** [comment]
@xuxuzhou checkout https://github.com/ruotianluo/self-critical.pytorch

**Comment by xuxuzhou** [comment]
OK, Thanks a lot. I'll read it later.
