### ISSUE TITLE
I met an error during training

### ISSUE THREAD

**Issue by fearless77** [ruotianluo/ImageCaptioning.pytorch#60]
My settings are as follows.
But when I run this at about epoch 4, I got an error.

python train.py --id st --caption_model show_tell --input_json data/cocotalk.json --input_fc_dir data/cocotalk_fc --input_att_dir data/cocotalk_att --input_label_h5 data/cocotalk_label.h5 --batch_size 10 --learning_rate 5e-4 --learning_rate_decay_start 0 --scheduled_sampling_start 0 --checkpoint_path log_st --save_checkpoint_every 6000 --val_images_use 5000 --max_epochs 25 --language_eval 1
... ...
iter 46597 (epoch 4), train_loss = 2.205, time/batch = 0.031
Read data: 0.00450682640076
iter 46598 (epoch 4), train_loss = 2.765, time/batch = 0.032
Read data: 0.00444507598877
iter 46599 (epoch 4), train_loss = 2.254, time/batch = 0.032
Read data: 0.00438904762268
iter 46600 (epoch 4), train_loss = 2.694, time/batch = 0.032
Read data: 0.00441908836365
iter 46601 (epoch 4), train_loss = 2.554, time/batch = 0.027
Read data: 0.00471806526184
iter 46602 (epoch 4), train_loss = 2.412, time/batch = 0.032
Read data: 0.00471496582031
iter 46603 (epoch 4), train_loss = 2.393, time/batch = 0.032
Read data: 0.00447201728821
iter 46604 (epoch 4), train_loss = 2.570, time/batch = 0.032
Read data: 0.0047972202301
Fatal Python error: GC object already tracked
Aborted (core dumped)
---------------------------------------------------------------------------------------------
How can I solve this.

**Comment by ruotianluo** [comment]
Can you resume training?
