### ISSUE TITLE
What is att_feats?

### ISSUE THREAD

**Issue by LaiPiXiong** [ruotianluo/ImageCaptioning.pytorch#67]
I ever think that att_feats means feature map. But in att2inmodel, you said it is attention feats. It confused me much. Can you give me some advice, what is att_feats, and if I use res101, what is the size of att_feats?

**Comment by ruotianluo** [comment]
7x7x2048

**Comment by LaiPiXiong** [comment]
So this is feature map, isn't it?

**Comment by LaiPiXiong** [comment]
Please check line 117 of  Att2inmodel.py . Thanks for your reply, I think i see.
