### ISSUE TITLE
Where is your resnet 101 Link?

### ISSUE THREAD

**Issue by he159ok** [ruotianluo/ImageCaptioning.pytorch#90]
Hi, when I run your code, it reminds me that the resnet101.pth is required. Can you tell me where is your weight parameters to download this resnet101.pth? Since I have tried other resnet101.pth from other source, the dimensions of its att_feats is (10, 196, 2048), where the fc_feats is (10, 2048), so that they can not converted to GPU directly, by transforming them into FloatTeansor.

In your eval_utils.py,

        tmp = [data['fc_feats'][np.arange(loader.batch_size) * loader.seq_per_img], 
            data['att_feats'][np.arange(loader.batch_size) * loader.seq_per_img],
            data['att_masks'][np.arange(loader.batch_size) * loader.seq_per_img] if data['att_masks'] is not None else None]
        tmp = [_.cuda() if _ is not None else _ for _ in tmp]

        #tmp = torch.FloatTensor(tmp)

        fc_feats, att_feats, att_masks = tmp
        # fc_feats = torch.FloatTensor(fc_feats)
        # att_feats = torch.FloatTensor(att_feats)
        # if att_masks != None:
        #     att_masks = torch.FloatTensor(att_masks)

I do like this, but the dimensions are not matched between fc_feats and att_feats.

**Comment by Tetsujinfr** [comment]
there is a link to download it [here](https://github.com/ruotianluo/ImageCaptioning.pytorch/tree/master/data) (it could be clearer in the repo main readme but by going under the data folder there was this "data" sub-readme all a sudden). hope this helps the next generations.

**Comment by ruotianluo** [comment]
The main reason it goes to sub-readme is because it seems a little bit too verbose in the main. Especially there are multiple choices for the feature to use.

**Comment by Tetsujinfr** [comment]
Maybe just put a link to the sub readme in the main readme. You do not need to add any text, just a hyperlink when you mention the need to get the resnet101 pretrained weights? Case closed anyway, no big deal.

**Comment by ruotianluo** [comment]
updated.
