### ISSUE TITLE
Question about the LayerNorm optimization in AoAModel

### ISSUE THREAD

**Issue by zyj0021200** [ruotianluo/ImageCaptioning.pytorch#97]
Hello and I'm a little confused about the LayerNorm optimization applied in AoAModel. According to the equation (7) in the original paper, the layer normalization was applied after the residual connection like:
A'=**LayerNorm**(A+AoA^E(A,...))
So in my opinion, after N times of stacking, the output A' should be like:

A1=**LN**(A+AoA^E(A,...))
A2=**LN**(A1+AoA^E(A1,...))
A3=**LN**(A2+AoA^E(A2,...))
......
A'=**LN**(A_N-1+AoA^E(A_N-1,...))

But the **SublayerConnection** in the code returns:
`x + self.dropout(sublayer(self.norm(x)))`
And **self.norm** is only applied once after N times of stacking in **AoA_Refiner_Core**, which seems to be like:

A1=A+AoA^E(**LN**(A),...)
A2=A1+AoA^E(**LN**(A1),...)
A3=A2+AoA^E(**LN**(A2),...)
......
A'=A_N-1+AoA^E(**LN**(A_N-1),...)
A'=**LN**(A')

Will such inconsistency lead to changes in the performance? Or it's just my misunderstanding of the paper?

**Comment by ruotianluo** [comment]
This is copied from aoanet repo.  You better ask there.
